# Generated by Django 4.1.1 on 2022-10-23 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_post_author_alter_post_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Games', 'Games'), ('Scottie Barnes', 'Scottie Barnes'), ('Pascal Siakam', 'Pascal Siakam'), ('Kawhi Leonard', 'Kawhi Leonard')], help_text='Name of the topic', max_length=20)),
                ('slug', models.SlugField(help_text='Slug for the topic', unique=True)),
            ],
        ),
    ]
