# Generated by Django 4.1.1 on 2022-10-23 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='name',
            field=models.CharField(choices=[('Games', 'Games'), ('Scottie Barnes', 'Scottie Barnes'), ('Pascal Siakam', 'Pascal Siakam'), ('Kawhi Leonard', 'Kawhi Leonard')], default='Games', help_text='Name of the topic', max_length=20),
        ),
        migrations.AlterField(
            model_name='topic',
            name='name',
            field=models.CharField(choices=[('Games', 'Games'), ('Scottie Barnes', 'Scottie Barnes'), ('Pascal Siakam', 'Pascal Siakam'), ('Kawhi Leonard', 'Kawhi Leonard')], default='Games', help_text='Name of the topic', max_length=20),
        ),
    ]
