# Generated by Django 4.1.1 on 2022-10-23 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_post_name_alter_topic_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='name',
            new_name='topic',
        ),
    ]
