# Generated by Django 4.1.1 on 2022-11-06 23:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_alter_comment_email_alter_comment_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='published',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, help_text='The date & time this article was published', null=True),
        ),
    ]
