# Generated by Django 4.1.1 on 2022-11-06 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_alter_post_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='published',
            field=models.DateTimeField(auto_now=True, help_text='The date & time this article was published', null=True),
        ),
    ]
